### Read all films with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/films

### Create a film
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title":"Barbie",
    "duration":170,
    "budget":10,
    "link":"https://fr.wikipedia.org/wiki/Barbie_(film)"
}


### delete a film 
DELETE {{baseUrl}}/films/3


### Update the film identified by id
PATCH {{baseUrl}}/films/1
Content-Type: application/json

{
    "title":"Magic Green 2",
    "duration":130
}
